In [4]:
import pandas as pd
import numpy as np

In [5]:
Enrol_1 = pd.read_csv('Enrolment1.csv')
Enrol_2 = pd.read_csv('Enrolment2.csv')
Enrol_3 = pd.read_csv('Enrolment3.csv')

In [6]:
Enrol_1.head()

,date,state,district,pincode,age_0_5,age_5_17,age_18_greater
0,02-03-2025,Meghalaya,East Khasi Hills,793121,11,61,37
1,09-03-2025,Karnataka,Bengaluru Urban,560043,14,33,39
2,09-03-2025,Uttar Pradesh,Kanpur Nagar,208001,29,82,12
3,09-03-2025,Uttar Pradesh,Aligarh,202133,62,29,15
4,09-03-2025,Karnataka,Bengaluru Urban,560016,14,16,21

In [7]:
Enrol_2.head()

,date,state,district,pincode,age_0_5,age_5_17,age_18_greater
0,26-10-2025,Andhra Pradesh,Nalgonda,508004,0,1,0
1,26-10-2025,Andhra Pradesh,Nalgonda,508238,1,0,0
2,26-10-2025,Andhra Pradesh,Nalgonda,508278,1,0,0
3,26-10-2025,Andhra Pradesh,Nandyal,518432,0,1,0
4,26-10-2025,Andhra Pradesh,Nandyal,518543,1,0,0

In [8]:
Enrol_3.head()

         date      state district  pincode  age_0_5  age_5_17  age_18_greater
0  31-12-2025  Karnataka    Bidar   585330        2         3               0
1  31-12-2025  Karnataka    Bidar   585402        6         0               0
2  31-12-2025  Karnataka    Bidar   585413        1         0               0
3  31-12-2025  Karnataka    Bidar   585418        1         2               0
4  31-12-2025  Karnataka    Bidar   585421        4         3               0

In [9]:
Enrol_1.shape

(500000, 7)

In [10]:
Enrol_2.shape

(500000, 7)

In [11]:
Enrol_3.shape

(6029, 7)

In [12]:
Enrol_1['state'].unique()

array(['Meghalaya', 'Karnataka', 'Uttar Pradesh', 'Bihar', 'Maharashtra',
       'Haryana', 'Rajasthan', 'Punjab', 'Delhi', 'Madhya Pradesh',
       'West Bengal', 'Assam', 'Uttarakhand', 'Gujarat', 'Andhra Pradesh',
       'Tamil Nadu', 'Chhattisgarh', 'Jharkhand', 'Nagaland', 'Manipur',
       'Telangana', 'Tripura', 'Mizoram', 'Jammu and Kashmir',
       'Chandigarh', 'Sikkim', 'Odisha', 'Kerala',
       'The Dadra And Nagar Haveli And Daman And Diu',
       'Arunachal Pradesh', 'Himachal Pradesh', 'Goa',
       'Jammu And Kashmir', 'Dadra and Nagar Haveli and Daman and Diu',
       'Ladakh', 'Andaman and Nicobar Islands', 'Orissa', 'Pondicherry',
       'Puducherry', 'Lakshadweep', 'Andaman & Nicobar Islands',
       'Dadra & Nagar Haveli', 'Dadra and Nagar Haveli', 'Daman and Diu',
       'WEST BENGAL', 'Jammu & Kashmir', 'West  Bengal', '100000',
       'Daman & Diu', 'West Bangal', 'Westbengal', 'West bengal',
       'andhra pradesh', 'ODISHA'], dtype=object)

In [13]:
df = pd.concat([Enrol_1,Enrol_2,Enrol_3],axis=0,ignore_index=True)

In [14]:
df.shape

(1006029, 7)

In [15]:
df.head()

,date,state,district,pincode,age_0_5,age_5_17,age_18_greater
0,02-03-2025,Meghalaya,East Khasi Hills,793121,11,61,37
1,09-03-2025,Karnataka,Bengaluru Urban,560043,14,33,39
2,09-03-2025,Uttar Pradesh,Kanpur Nagar,208001,29,82,12
3,09-03-2025,Uttar Pradesh,Aligarh,202133,62,29,15
4,09-03-2025,Karnataka,Bengaluru Urban,560016,14,16,21

In [16]:
df['state']

0              Meghalaya
1              Karnataka
2          Uttar Pradesh
3          Uttar Pradesh
4              Karnataka
               ...
1006024      West Bengal
1006025      West Bengal
1006026      West Bengal
1006027      West Bengal
1006028      West Bengal
Name: state, Length: 1006029, dtype: object

In [17]:
df['state'] = df['state'].str.strip()

In [18]:
df.head()

,date,state,district,pincode,age_0_5,age_5_17,age_18_greater
0,02-03-2025,Meghalaya,East Khasi Hills,793121,11,61,37
1,09-03-2025,Karnataka,Bengaluru Urban,560043,14,33,39
2,09-03-2025,Uttar Pradesh,Kanpur Nagar,208001,29,82,12
3,09-03-2025,Uttar Pradesh,Aligarh,202133,62,29,15
4,09-03-2025,Karnataka,Bengaluru Urban,560016,14,16,21

In [19]:
df['state'].nunique()

55

In [20]:
df.isna().sum()

date              0
state             0
district          0
pincode           0
age_0_5           0
age_5_17          0
age_18_greater    0
dtype: int64

In [21]:
df['state'] = df['state'].str.lower()
df['district'] = df['district'].str.lower()

In [22]:
df.head()

,date,state,district,pincode,age_0_5,age_5_17,age_18_greater
0,02-03-2025,meghalaya,east khasi hills,793121,11,61,37
1,09-03-2025,karnataka,bengaluru urban,560043,14,33,39
2,09-03-2025,uttar pradesh,kanpur nagar,208001,29,82,12
3,09-03-2025,uttar pradesh,aligarh,202133,62,29,15
4,09-03-2025,karnataka,bengaluru urban,560016,14,16,21

In [23]:
df['state'] = df['state'].str.replace(r'\bthe\b', '', regex=True).str.strip()

In [24]:
df.head()

,date,state,district,pincode,age_0_5,age_5_17,age_18_greater
0,02-03-2025,meghalaya,east khasi hills,793121,11,61,37
1,09-03-2025,karnataka,bengaluru urban,560043,14,33,39
2,09-03-2025,uttar pradesh,kanpur nagar,208001,29,82,12
3,09-03-2025,uttar pradesh,aligarh,202133,62,29,15
4,09-03-2025,karnataka,bengaluru urban,560016,14,16,21

In [25]:
print(df['state'].unique())

['meghalaya' 'karnataka' 'uttar pradesh' 'bihar' 'maharashtra' 'haryana'
 'rajasthan' 'punjab' 'delhi' 'madhya pradesh' 'west bengal' 'assam'
 'uttarakhand' 'gujarat' 'andhra pradesh' 'tamil nadu' 'chhattisgarh'
 'jharkhand' 'nagaland' 'manipur' 'telangana' 'tripura' 'mizoram'
 'jammu and kashmir' 'chandigarh' 'sikkim' 'odisha' 'kerala'
 'dadra and nagar haveli and daman and diu' 'arunachal pradesh'
 'himachal pradesh' 'goa' 'ladakh' 'andaman and nicobar islands' 'orissa'
 'pondicherry' 'puducherry' 'lakshadweep' 'andaman & nicobar islands'
 'dadra & nagar haveli' 'dadra and nagar haveli' 'daman and diu'
 'jammu & kashmir' 'west  bengal' '100000' 'daman & diu' 'west bangal'
 'westbengal']

In [26]:
df['state'].nunique()
df1 = df

In [27]:
df[df['state'] == '100000'].shape

(22, 7)

In [28]:
df['state'].dtype

dtype('O')

In [29]:
df['state'] = df['state'].replace({
    'west bangal': 'west bengal',
    'westbengal': 'west bengal',
    'west  bengal': 'west bengal'
})

In [30]:
df.head()

,date,state,district,pincode,age_0_5,age_5_17,age_18_greater
0,02-03-2025,meghalaya,east khasi hills,793121,11,61,37
1,09-03-2025,karnataka,bengaluru urban,560043,14,33,39
2,09-03-2025,uttar pradesh,kanpur nagar,208001,29,82,12
3,09-03-2025,uttar pradesh,aligarh,202133,62,29,15
4,09-03-2025,karnataka,bengaluru urban,560016,14,16,21

In [31]:
df['state'].nunique()

45

In [32]:
df['state'].unique()

array(['meghalaya', 'karnataka', 'uttar pradesh', 'bihar', 'maharashtra',
       'haryana', 'rajasthan', 'punjab', 'delhi', 'madhya pradesh',
       'west bengal', 'assam', 'uttarakhand', 'gujarat', 'andhra pradesh',
       'tamil nadu', 'chhattisgarh', 'jharkhand', 'nagaland', 'manipur',
       'telangana', 'tripura', 'mizoram', 'jammu and kashmir',
       'chandigarh', 'sikkim', 'odisha', 'kerala',
       'dadra and nagar haveli and daman and diu', 'arunachal pradesh',
       'himachal pradesh', 'goa', 'ladakh', 'andaman and nicobar islands',
       'orissa', 'pondicherry', 'puducherry', 'lakshadweep',
       'andaman & nicobar islands', 'dadra & nagar haveli',
       'dadra and nagar haveli', 'daman and diu', 'jammu & kashmir',
       '100000', 'daman & diu'], dtype=object)

In [33]:
df['state'] = df['state'].replace({'orissa' :'odisha'})

In [34]:
df['state'].nunique()

44

In [35]:
df[df['state'] == 'dadra and nagar haveli and daman and diu']

,date,state,district,pincode,age_0_5,age_5_17,age_18_greater
1604,01-06-2025,dadra and nagar haveli and daman and diu,dadra and nagar haveli,396230,188,49,12
2895,01-07-2025,dadra and nagar haveli and daman and diu,dadra and nagar haveli,396230,360,92,15
3806,01-09-2025,dadra and nagar haveli and daman and diu,dadra and nagar haveli,396230,0,1,0
27677,02-09-2025,dadra and nagar haveli and daman and diu,daman,396210,1,0,0
35283,03-09-2025,dadra and nagar haveli and daman and diu,dadra and nagar haveli,396230,1,0,0
...,...,...,...,...,...,...,...
956542,27-12-2025,dadra and nagar haveli and daman and diu,daman,396210,0,0,1
984102,29-12-2025,dadra and nagar haveli and daman and diu,diu,362520,1,0,0
992518,31-12-2025,dadra and nagar haveli and daman and diu,daman,396210,1,0,0
992519,31-12-2025,dadra and nagar haveli and daman and diu,diu,362540,1,0,0
996925,31-12-2025,dadra and nagar haveli and daman and diu,daman,396220,0,0,1

In [36]:
df[df['state'] == 'dadra and nagar haveli']

,date,state,district,pincode,age_0_5,age_5_17,age_18_greater
11060,01-09-2025,dadra and nagar haveli,dadra and nagar haveli,396235,1,0,0
14231,01-09-2025,dadra and nagar haveli,dadra and nagar haveli,396193,1,0,0
18324,01-09-2025,dadra and nagar haveli,dadra and nagar haveli,396230,14,0,0
23695,02-09-2025,dadra and nagar haveli,dadra and nagar haveli,396230,10,3,0
27676,02-09-2025,dadra and nagar haveli,dadra and nagar haveli,396240,3,0,0
...,...,...,...,...,...,...,...
954061,27-12-2025,dadra and nagar haveli,dadra and nagar haveli,396235,0,1,0
974232,29-12-2025,dadra and nagar haveli,dadra and nagar haveli,396235,1,0,0
984101,29-12-2025,dadra and nagar haveli,dadra and nagar haveli,396230,4,2,0
992517,31-12-2025,dadra and nagar haveli,dadra and nagar haveli,396240,4,0,0
996924,31-12-2025,dadra and nagar haveli,dadra and nagar haveli,396230,10,1,1

In [37]:
df[df['state'] == 'daman and diu']

,date,state,district,pincode,age_0_5,age_5_17,age_18_greater
11061,01-09-2025,daman and diu,daman,396210,2,1,0
23696,02-09-2025,daman and diu,daman,396210,1,0,0
42227,03-09-2025,daman and diu,daman,396215,0,1,0
104995,08-09-2025,daman and diu,diu,362570,1,0,0
108247,09-09-2025,daman and diu,daman,396210,1,0,0
...,...,...,...,...,...,...,...
959613,27-12-2025,daman and diu,diu,362540,1,0,0
961472,27-12-2025,daman and diu,diu,362540,1,0,0
974233,29-12-2025,daman and diu,diu,362520,1,0,0
982244,29-12-2025,daman and diu,daman,396215,1,0,0
1003075,31-12-2025,daman and diu,daman,396215,0,1,0

In [38]:
df2 = df

In [39]:
df['state'] = df['state'].replace({ 'daman and diu':'dadra and nagar haveli and daman and diu',
                                    'dadra and nagar haveli': 'dadra and nagar haveli and daman and diu',
                                    'dadra & nagar haveli' : 'dadra and nagar haveli and daman and diu',
                                    'dadra and nagar haveli and daman and diu': 'dadra and nagar haveli and daman and diu',
                                    'daman & diu' : 'dadra and nagar haveli and daman and diu'
                                  })

In [40]:
df['state'] = df['state'].replace({'jammu & kashmir' : 'jammu and kashmir',
                                   'andaman & nicobar islands' :  'andaman and nicobar islands',
                                   'pondicherry' : 'puducherry'
                                  })

In [41]:
df['state'].unique()

array(['meghalaya', 'karnataka', 'uttar pradesh', 'bihar', 'maharashtra',
       'haryana', 'rajasthan', 'punjab', 'delhi', 'madhya pradesh',
       'west bengal', 'assam', 'uttarakhand', 'gujarat', 'andhra pradesh',
       'tamil nadu', 'chhattisgarh', 'jharkhand', 'nagaland', 'manipur',
       'telangana', 'tripura', 'mizoram', 'jammu and kashmir',
       'chandigarh', 'sikkim', 'odisha', 'kerala',
       'dadra and nagar haveli and daman and diu', 'arunachal pradesh',
       'himachal pradesh', 'goa', 'ladakh', 'andaman and nicobar islands',
       'puducherry', 'lakshadweep', '100000'], dtype=object)

In [42]:
df = df[df['state'] != '100000']

In [43]:
df['state'].nunique()

36

In [44]:
df['district'].unique()

array(['east khasi hills', 'bengaluru urban', 'kanpur nagar', 'aligarh',
       'sitamarhi', 'bahraich', 'firozabad', 'purbi champaran',
       'maharajganj', 'aurangabad', 'ghaziabad', 'faridabad', 'madhubani',
       'sikar', 'bhagalpur', 'amritsar', 'gurugram',
       'gautam buddha nagar', 'west delhi', 'bhind', 'gwalior', 'katni',
       'coochbehar', 'lucknow', 'dinajpur uttar', 'marigaon', 'kokrajhar',
       'agra', 'haridwar', 'nagaon', 'parbhani', 'west khasi hills',
       'north west delhi', 'west jaintia hills', 'unnao', 'saharanpur',
       'dibrugarh', 'udalguri', 'chirang', 'kamrup', 'dhubri', 'jaunpur',
       'thane', 'dhemaji', 'banas kantha', 'tinsukia', 'spsr nellore',
       'barpeta', 'sonitpur', 'baksa', 'ludhiana', 'patan', 'kanchipuram',
       'patna', 'lakhimpur', 'bongaigaon', 'vadodara', 'nainital',
       'dehradun', 'hojai', 'dohad', 'morbi', 'raipur', 'gorakhpur',
       'bulandshahr', 'mathura', 'pashchim champaran', 'bijapur',
       'deoghar', 'muzaffarpur', 'banda', 'kachchh', 'ri bhoi', 'darrang',
       'ashok nagar', 'darjeeling', 'north cachar hills', 'ranchi',
       'surat', 'nanded', 'bengaluru', 'jorhat', 'gir somnath',
       'kamrup metro', 'goalpara', 'bhavnagar', 'golaghat', 'nagpur',
       'cooch behar', 'jalgaon', 'hingoli', 'ahmadnagar', 'gandhinagar',
       'north 24 parganas', 'munger', 'kohima', 'jalor', 'kheda',
       'nalbari', 'palghar', 'jodhpur', 'central delhi', 'gaya',
       'sabarkantha', 'dimapur', 'cachar', 'banaskantha', 'kheri',
       'rajkot', 'satara', 'betul', 'west karbi anglong', 'south delhi',
       'raigad', 'uttar dinajpur', 'guna', 'kaimur (bhabua)', 'dholpur',
       'churachandpur', 'west champaran', 'bharuch', 'jhargram',
       'khargone', 'chhotaudepur', 'mumbai suburban', 'hailakandi',
       'panchmahals', 'south salmara mankachar', 'budaun', 'kanpur dehat',
       'porbandar', 'west garo hills', 'kapurthala', 'south garo hills',
       'nagaur', 'mysuru', 'mahesana', 'churu', 'hyderabad',
       'kancheepuram', 'varanasi', 'lohardaga', 'north garo hills',
       'chhatarpur', 'nadia', 'purnia', 'gurgaon', 'charaideo', 'jaipur',
       'saran', 'morena', 'dhar', 'dahod', 'devbhumi dwarka',
       'east champaran', 'tapi', 'baghpat', 'fatehpur',
       'south west khasi hills', 'yadgir', 'nandurbar', 'etawah',
       'jalpaiguri', 'jabalpur', 'shamli', 'sibsagar', 'barwani', 'botad',
       'junagadh', 'balrampur', 'bara banki', 'shivpuri', 'beed',
       'shahjahanpur', 'jamnagar', 'chandrapur', 'durg',
       'k.v. rangareddy', 'sirohi', 'alipurduar', 'south west delhi',
       'gonda', 'east jaintia hills', 'bareilly', 'bundi', 'solapur',
       'sitapur', 'dumka', 'sultanpur', 'karbi anglong', 'bikaner',
       'phek', 'raisen', 'shrawasti', 'east delhi', 'jhabua', 'unakoti',
       'indore', 'bhopal', 'dungarpur', 'chandauli', 'bharatpur',
       'mainpuri', 'godda', 'muzaffarnagar', 'siddharthnagar', 'datia',
       'west tripura', 'medchal-malkajgiri', 'sagar', 'sheopur',
       'arvalli', 'surendra nagar', 'malda', 'amreli', 'alwar',
       'ambedkar nagar', 'madurai', 'pilibhit', 'champhai', 'valsad',
       'pakur', 'vaishali', 'vidisha', 'karimganj', 'biswanath',
       'burhanpur', 'kaushambi', 'pune', 'punch', 'jehanabad', 'jalaun',
       'etah', 'meerut', 'baran', 'sangrur', 'karauli', 'anand',
       'longleng', 'chandigarh', 'jamui', 'south sikkim', 'panna',
       'east garo hills', 'jhalawar', 'shahdara', 'kalaburagi',
       'thanjavur', 'peren', 'tuensang', 'mahisagar', 'hoshiarpur',
       'noklak', 'sukma', 'khandwa', 'ajmer', 'west sikkim', 'latur',
       'basti', 'satna', 'gurdaspur', 'hazaribagh', 'azamgarh', 'udaipur',
       'kolkata', 'rampur', 'the dangs', 'east singhbhum', 'alirajpur',
       'sas nagar (mohali)', 'south west garo hills', 'moradabad', 'kota',
       'dewas', 'navsari', 'chumukedima', 'ahmedabad', 'nabarangapur',
       'pali', 'amroha', 'saiha', 'dakshin dinajpur', 'bijnor',
       'pudukkottai', 'bangalore rural', 'kalimpong', 'deoria',
       'baramula', 'gopalganj', 'prayagraj', 'lalitpur', 'mewat', 'hapur',
       'jammu', 'bishnupur', 'saharsa', 'arwal', 'hathras', 'lawngtlai',
       'nashik', 'yavatmal', 'cuddalore', 'kollam', 'patiala', 'katihar',
       'malappuram', 'birbhum', 'siwan', 'dhule', 'baloda bazar',
       'washim', 'coimbatore', 'lunglei', 'imphal west', 'kushinagar',
       'thiruvananthapuram', 'sangli', 'ahmadabad', 'lakhisarai',
       'bengaluru rural', '24 paraganas north', 'dima hasao', 'banka',
       'salem', 'dadra and nagar haveli', 'dang', 'kaithal', 'vellore',
       'shravasti', 'nalanda', 'jaisalmer', 'kallakurichi', 'farrukhabad',
       'medinipur west', 'araria', 'sonipat', 'chatra',
       'gaurella pendra marwahi', 'visakhapatanam', 'buldhana',
       'amravati', 'hardoi', 'dhalai', 'ernakulam', 'new delhi',
       'bhilwara', 'ramanathapuram', 'mon', 'raichur', 'north delhi',
       'rohtak', 'gumla', 'barmer', 'kurukshetra', 'nuh', 'ashoknagar',
       'thrissur', 's.a.s nagar', 'north east delhi', 'purba bardhaman',
       'ambala', 'panipat', 'darbhanga', 'ayodhya', 'khunti',
       'medchal malkajgiri', 'sivasagar', 'hisar', 'sivaganga',
       'siddharth nagar', 'west kameng', 'kullu', 'khordha', 'barabanki',
       'chengalpattu', 'ahmednagar', 'jalore', 'nawada', 'hooghly',
       '24 paraganas south', 'chennai', 'surendranagar', 'mumbai',
       'nabarangpur', 'sabar kantha', 'ramanagara', 'wokha',
       'west singhbhum', 'sepahijala', 'samastipur', 'zunheboto',
       'east singhbum', 'sambhal', 'chittorgarh', 'panch mahals', 'bidar',
       'tonk', 'longding', 'jhansi', 'howrah', 'raigarh', 'giridih',
       'akola', 'north goa', 'vijayapura', 'begusarai', 'ranga reddy',
       'thiruvallur', 'bhadradri kothagudem', 'hanumangarh', 'kannur',
       'tarn taran', 'majuli', 'balaghat', 'kiphire', 'dinajpur dakshin',
       'east nimar', 'osmanabad', 'dhanbad', 'kasganj', 'shopian',
       'sehore', 'kannauj', 'narsinghpur', 'bilaspur', 'kolasib',
       'sawai madhopur', 'north tripura', 'kushi nagar', 'prakasam',
       'bhojpur', 'hoshangabad', 'doda', 'mokokchung', 'gomati',
       'krishna', 'kurnool', 'mahabub nagar', 'mahbubnagar', 'medak',
       'n. t. r', 'nalgonda', 'nandyal', 'nellore', 'palnadu',
       'rangareddi', 'sri potti sriramulu nellore', 'sri sathya sai',
       'srikakulam', 'tirupati', 'visakhapatnam', 'vizianagaram',
       'warangal', 'west godavari', 'y. s. r', 'changlang', 'east kameng',
       'tawang', 'west siang', 'bajali', 'sribhumi', 'buxar', 'khagaria',
       'kishanganj', 'madhepura', 'rohtas', 'sheohar', 'supaul', 'bastar',
       'bemetara', 'gariyaband', 'jashpur', 'kawardha', 'kondagaon',
       'korba', 'manendragarh–chirmiri–bharatpur', 'rajnandgaon', 'sakti',
       'sarangarh-bilaigarh', 'surajpur', 'surguja', 'south goa',
       'narmada', 'bhiwani', 'charkhi dadri', 'fatehabad', 'jhajjar',
       'jind', 'karnal', 'mahendragarh', 'rewari', 'sirsa',
       'yamuna nagar', 'hamirpur', 'kangra', 'mandi', 'sirmaur', 'solan',
       'una', 'anantnag', 'badgam', 'bandipore', 'budgam', 'kargil',
       'kathua', 'kupwara', 'leh', 'pulwama', 'rajouri', 'ramban',
       'reasi', 'samba', 'srinagar', 'udhampur', 'bokaro', 'garhwa',
       'garhwa *', 'hazaribag', 'jamtara', 'latehar', 'palamau', 'palamu',
       'purbi singhbhum', 'ramgarh', 'sahebganj', 'seraikela-kharsawan',
       'simdega', 'bagalkot', 'bagalkot *', 'ballari', 'bangalore',
       'belagavi', 'belgaum', 'bellary', 'chamarajanagar',
       'chamrajanagar', 'chamrajnagar', 'chickmagalur', 'chikkaballapur',
       'chikkamagaluru', 'chikmagalur', 'chitradurga', 'dakshina kannada',
       'davanagere', 'davangere', 'dharwad', 'gadag', 'gadag *',
       'gulbarga', 'hassan', 'haveri', 'kodagu', 'kolar', 'koppal',
       'mandya', 'mysore', 'ramanagar', 'shimoga', 'shivamogga',
       'tumakuru', 'tumkur', 'udupi', 'uttara kannada', 'vijayanagara',
       'alappuzha', 'idukki', 'kasaragod', 'kasargod', 'kottayam',
       'kozhikode', 'palakkad', 'pathanamthitta', 'wayanad', 'agar malwa',
       'anuppur', 'chhindwara', 'damoh', 'dindori', 'harda', 'maihar',
       'mandla', 'mandsaur', 'narmadapuram', 'narsimhapur', 'neemuch',
       'niwari', 'rajgarh', 'ratlam', 'rewa', 'seoni', 'shahdol',
       'shajapur', 'sidhi', 'singrauli', 'tikamgarh', 'ujjain',
       'west nimar', 'ahmed nagar', 'bhandara', 'buldana',
       'chhatrapati sambhajinagar', 'gadchiroli', 'gondiya', 'jalna',
       'kolhapur', 'mumbai city', 'ratnagiri', 'sindhudurg', 'wardha',
       'senapati', 'tamenglong', 'aizawl', 'angul', 'nicobar',
       'south andaman', 'adilabad', 'alluri sitharama raju', 'anakapalli',
       'anantapur', 'ananthapur', 'ananthapuramu', 'bapatla', 'chittoor',
       'cuddapah', 'dr. b. r. ambedkar konaseema', 'east godavari',
       'eluru', 'guntur', 'kakinada', 'karimnagar', 'khammam', 'anugul',
       'balangir', 'baleswar', 'bargarh', 'baudh', 'bhadrak', 'boudh',
       'cuttack', 'debagarh', 'dhenkanal', 'gajapati', 'ganjam', 'jajpur',
       'jagatsinghapur', 'jagatsinghpur', 'jajapur', 'kalahandi',
       'kandhamal', 'kendrapara', 'kendujhar', 'khorda', 'koraput',
       'malkangiri', 'mayurbhanj', 'nayagarh', 'nuapada', 'puri',
       'rayagada', 'sambalpur', 'sonapur', 'subarnapur', 'sundargarh',
       'sundergarh', 'baleshwar', 'pondicherry', 'karaikal', 'puducherry',
       'yanam', 'barnala', 'bathinda', 'faridkot', 'fatehgarh sahib',
       'ferozepur', 'firozpur', 'jalandhar', 'malerkotla', 'mansa',
       'muktsar', 'pathankot', 'rupnagar', 'shaheed bhagat singh nagar',
       'sri muktsar sahib', 'banswara', 'chittaurgarh', 'dausa',
       'ganganagar', 'jhunjhunun', 'pratapgarh', 'rajsamand', 'east',
       'north sikkim', 'south', 'ariyalur', 'dharmapuri', 'dindigul',
       'erode', 'kanniyakumari', 'kanyakumari', 'karur', 'krishnagiri',
       'mayiladuthurai', 'nagapattinam', 'namakkal', 'perambalur',
       'ranipet', 'tenkasi', 'the nilgiris', 'theni', 'thiruvarur',
       'thoothukkudi', 'tiruchirappalli', 'tirunelveli', 'tirupattur',
       'tiruppur', 'tiruvallur', 'tiruvannamalai', 'villupuram',
       'viluppuram', 'virudhunagar', 'hanumakonda', 'jagitial', 'jangoan',
       'jayashankar bhupalpally', 'jogulamba gadwal', 'kamareddy',
       'komaram bheem', 'mahabubabad', 'mahabubnagar', 'mancherial',
       'medchal−malkajgiri', 'mulugu', 'nagarkurnool', 'narayanpet',
       'nirmal', 'nizamabad', 'peddapalli', 'rajanna sircilla',
       'sangareddy', 'siddipet', 'suryapet', 'vikarabad', 'wanaparthy',
       'warangal rural', 'warangal urban', 'yadadri.', 'khowai',
       'south tripura', 'allahabad', 'amethi', 'auraiya', 'ballia',
       'bhadohi', 'chitrakoot', 'faizabad', 'ghazipur', 'mahoba', 'mau',
       'mirzapur', 'rae bareli', 'sant kabir nagar', 'sant ravidas nagar',
       'sonbhadra', 'almora', 'bageshwar', 'chamoli', 'garhwal',
       'pauri garhwal', 'pithoragarh', 'rudraprayag', 'tehri garhwal',
       'udham singh nagar', 'uttarkashi', 'bankura', 'barddhaman',
       'bardhaman', 'darjiling', 'east midnapore', 'haora', 'koch bihar',
       'maldah', 'murshidabad', 'north twenty four parganas',
       'paschim bardhaman', 'paschim medinipur', 'purba medinipur',
       'purulia', 'puruliya', 'south 24 parganas', 'south dinajpur',
       'south twenty four parganas', 'west midnapore', 'north east',
       'parvathipuram manyam', 'kurung kumey', 'lohit',
       'lower dibang valley', 'papum pare', 'upper siang',
       'aurangabad(bh)', 'purba champaran', 'purnea', 'sheikhpura',
       'balod', 'dhamtari', 'gaurela-pendra-marwahi', 'janjgir-champa',
       'kabeerdham', 'kanker', 'khairagarh chhuikhadan gandai', 'koriya',
       'mahasamund', 'mohla-manpur-ambagarh chouki', 'mungeli',
       'narayanpur', 'palwal', 'chamba', 'shimla', 'ganderbal', 'kodarma',
       'pakaur', 'sahibganj', 'hasan', 'lakshadweep', 'harda *',
       'mauganj', 'umaria', 'chatrapati sambhaji nagar',
       'mumbai( sub urban )', 'nandurbar *', 'imphal east', 'thoubal',
       'ukhrul', 'eastern west khasi hills', 'mamit', 'serchhip',
       'andamans', 'north and middle andaman', 'annamayya',
       'k.v.rangareddy', 'karim nagar', 'rangareddy', 'bulandshahar',
       'hugli', 'north dinajpur', 'jharsuguda', 'fazilka', 'moga',
       'north', 'chandel', 'kakching', 's.a.s nagar(mohali)', 'jhunjhunu',
       'east sikkim', 'west', 'lower subansiri', 'namsai', 'sheikpura',
       'dakshin bastar dantewada', 'dadra & nagar haveli', 'daman',
       'panchkula', 'kishtwar', 'shupiyan', 'pashchimi singhbhum',
       'pandhurna', 'bid', 'gondiya *', 'jyotiba phule nagar',
       'sant ravidas nagar bhadohi', 'meluri', 'dhaulpur', 'anjaw',
       'east siang', 'tamulpur district', 'dantewada', 'koderma',
       'chamarajanagar *', 'dharashiv', 'gondia', 'dhalai  *', 'kulgam',
       'jiribam', 'saitual', 'kra daadi', 'upper subansiri', 'bhabua',
       'champawat', 'kamle', 'haveri *', 'mammit', 'shamator',
       'nawanshahr', 'jangaon', 'monghyr', 'uttar bastar kanker',
       'south east delhi', 'samstipur', 'diu', 'najafgarh', 'kinnaur',
       'tuticorin', 'warangal (urban)', 'siang', 'tirap', 'namchi',
       'hardwar', 'niuland', 'shi-yomi', 'khawzawl', 'janjgir - champa',
       'lahul and spiti', 'janjgir champa', 'washim *', 'nicobars',
       'lower siang', 'yamunanagar', 'lahul & spiti', 'jhajjar *',
       'raebareli', 'hawrah', 'bengaluru south', 'raigarh(mh)',
       'tirupathur', 'dibang valley', 'deeg\xa0', 'leparada',
       'medchal?malkajgiri', 'medinipur',
       'mohalla-manpur-ambagarh chowki', 'tseminyu', 'mahrajganj',
       'hnahthial', 'pakke kessang', 'kushinagar *', 'tiruvarur',
       'east midnapur', 'hingoli *', 'north east   *', 'bardez',
       'namakkal   *', 'hooghiy', 'pherzawl', 'jaintia hills',
       'west medinipur', 'lahaul and spiti', 'burdwan', 'bandipur',
       'mangan', 'leh (ladakh)', 'bokaro *', 'south 24 pargana', 'deeg',
       'anugal', 'udupi *', 'kendrapara *', 'rajauri', 'bijapur(kar)',
       'bagpat', 'balotra', 'ahilyanagar', 'didwana-kuchaman', 'salumbar',
       'beawar'], dtype=object)

In [45]:
df.shape

(1006007, 7)

In [46]:
df = df.copy()   # now it's independent
df['district'] = df['district'].str.strip()
df['district'] = df['district'].str.replace(r'\s+', ' ', regex=True)
df['district'] = df['district'].str.lower()

In [47]:
df

,date,state,district,pincode,age_0_5,age_5_17,age_18_greater
0,02-03-2025,meghalaya,east khasi hills,793121,11,61,37
1,09-03-2025,karnataka,bengaluru urban,560043,14,33,39
2,09-03-2025,uttar pradesh,kanpur nagar,208001,29,82,12
3,09-03-2025,uttar pradesh,aligarh,202133,62,29,15
4,09-03-2025,karnataka,bengaluru urban,560016,14,16,21
...,...,...,...,...,...,...,...
1006024,31-12-2025,west bengal,west midnapore,721149,2,0,0
1006025,31-12-2025,west bengal,west midnapore,721150,2,2,0
1006026,31-12-2025,west bengal,west midnapore,721305,0,1,0
1006027,31-12-2025,west bengal,west midnapore,721504,1,0,0
1006028,31-12-2025,west bengal,west midnapore,721517,2,1,0

In [48]:
df['district'] = df['district'].str.replace(r'[^a-zA-Z0-9\s\-]', '', regex=True)

In [49]:
df

,date,state,district,pincode,age_0_5,age_5_17,age_18_greater
0,02-03-2025,meghalaya,east khasi hills,793121,11,61,37
1,09-03-2025,karnataka,bengaluru urban,560043,14,33,39
2,09-03-2025,uttar pradesh,kanpur nagar,208001,29,82,12
3,09-03-2025,uttar pradesh,aligarh,202133,62,29,15
4,09-03-2025,karnataka,bengaluru urban,560016,14,16,21
...,...,...,...,...,...,...,...
1006024,31-12-2025,west bengal,west midnapore,721149,2,0,0
1006025,31-12-2025,west bengal,west midnapore,721150,2,2,0
1006026,31-12-2025,west bengal,west midnapore,721305,0,1,0
1006027,31-12-2025,west bengal,west midnapore,721504,1,0,0
1006028,31-12-2025,west bengal,west midnapore,721517,2,1,0

In [50]:
df['state'].nunique()

36

In [51]:
df_guj = df[df['state'] == 'gujarat']

In [62]:
df_guj['district'].nunique()

40

In [54]:
df['state'] = (
    df['state']
    .str.strip()      # remove extra spaces
    .str.lower()      # make everything lowercase first
    .str.title()      # First letter capital
)

In [55]:
df

,date,state,district,pincode,age_0_5,age_5_17,age_18_greater
0,02-03-2025,Meghalaya,east khasi hills,793121,11,61,37
1,09-03-2025,Karnataka,bengaluru urban,560043,14,33,39
2,09-03-2025,Uttar Pradesh,kanpur nagar,208001,29,82,12
3,09-03-2025,Uttar Pradesh,aligarh,202133,62,29,15
4,09-03-2025,Karnataka,bengaluru urban,560016,14,16,21
...,...,...,...,...,...,...,...
1006024,31-12-2025,West Bengal,west midnapore,721149,2,0,0
1006025,31-12-2025,West Bengal,west midnapore,721150,2,2,0
1006026,31-12-2025,West Bengal,west midnapore,721305,0,1,0
1006027,31-12-2025,West Bengal,west midnapore,721504,1,0,0
1006028,31-12-2025,West Bengal,west midnapore,721517,2,1,0

In [57]:
df['state'].unique()

array(['Meghalaya', 'Karnataka', 'Uttar Pradesh', 'Bihar', 'Maharashtra',
       'Haryana', 'Rajasthan', 'Punjab', 'Delhi', 'Madhya Pradesh',
       'West Bengal', 'Assam', 'Uttarakhand', 'Gujarat', 'Andhra Pradesh',
       'Tamil Nadu', 'Chhattisgarh', 'Jharkhand', 'Nagaland', 'Manipur',
       'Telangana', 'Tripura', 'Mizoram', 'Jammu And Kashmir',
       'Chandigarh', 'Sikkim', 'Odisha', 'Kerala',
       'Dadra And Nagar Haveli And Daman And Diu', 'Arunachal Pradesh',
       'Himachal Pradesh', 'Goa', 'Ladakh', 'Andaman And Nicobar Islands',
       'Puducherry', 'Lakshadweep'], dtype=object)

In [58]:
state_fix = {
    'Jammu And Kashmir': 'Jammu and Kashmir',
    'Andaman And Nicobar Islands' : 'Andaman and Nicobar Islands',
    'Dadra And Nagar Haveli And Daman And Diu' : 'Dadra and Nagar Haveli and Daman and Diu'
}

df['state'] = df['state'].replace(state_fix)

In [61]:
df['state'].nunique()

36

In [63]:
df1 = df

In [88]:
gujarat_fix = {
    'banas kantha': 'Banaskantha',
    'banaskantha': 'Banaskantha',
    'sabar kantha': 'Sabarkantha',
    'sabarkantha': 'Sabarkantha',
    'panch mahals': 'Panchmahal',
    'panchmahals': 'Panchmahal',
    'surendra nagar': 'Surendranagar',
    'surendranagar': 'Surendranagar',
    'ahmadabad': 'Ahmedabad',
    'ahmedabad': 'Ahmedabad',
    'dohad': 'Dahod',
    'dahod': 'Dahod',
    'the dangs': 'Dang',
    'dang': 'Dang',
    'devbhumi dwarka': 'Devbhoomi Dwarka',
    'mahesana': 'Mehsana',
    'arvalli': 'Aravalli',
    'chhotaudepur': 'Chhota Udaipur',
    'gir somnath': 'Gir Somnath'
}
df['district'] = (
    df['district']
    .str.lower()
    .str.strip()
    .replace(gujarat_fix)
    .str.title()     # capitalize first letter of each word

)

In [89]:
df_guj = df[df['state'] == 'Gujarat']

In [90]:
df_guj['district'].unique()

array(['Banaskantha', 'Patan', 'Vadodara', 'Dahod', 'Morbi', 'Kachchh',
       'Surat', 'Gir Somnath', 'Bhavnagar', 'Gandhinagar', 'Kheda',
       'Sabarkantha', 'Rajkot', 'Bharuch', 'Chhota Udaipur', 'Panchmahal',
       'Porbandar', 'Mehsana', 'Devbhoomi Dwarka', 'Tapi', 'Botad',
       'Junagadh', 'Jamnagar', 'Aravalli', 'Surendranagar', 'Amreli',
       'Valsad', 'Anand', 'Mahisagar', 'Dang', 'Navsari', 'Ahmedabad',
       'Narmada'], dtype=object)

In [93]:
df_megha = df[df['state'] == 'Meghalaya']

In [94]:
df_megha['district'].unique()

array(['East Khasi Hills', 'West Khasi Hills', 'West Jaintia Hills',
       'Ri Bhoi', 'West Garo Hills', 'South Garo Hills',
       'North Garo Hills', 'South West Khasi Hills', 'East Jaintia Hills',
       'East Garo Hills', 'South West Garo Hills', 'Kamrup',
       'Eastern West Khasi Hills', 'Jaintia Hills'], dtype=object)

In [95]:
df_megha

,date,state,district,pincode,age_0_5,age_5_17,age_18_greater
0,02-03-2025,Meghalaya,East Khasi Hills,793121,11,61,37
46,15-03-2025,Meghalaya,West Khasi Hills,793119,34,10,148
54,15-03-2025,Meghalaya,West Jaintia Hills,793150,92,17,30
109,20-03-2025,Meghalaya,West Jaintia Hills,793150,55,10,95
115,20-03-2025,Meghalaya,West Khasi Hills,793119,20,19,202
...,...,...,...,...,...,...,...
1004461,31-12-2025,Meghalaya,South Garo Hills,794103,0,1,0
1004462,31-12-2025,Meghalaya,South West Garo Hills,794105,0,2,0
1004463,31-12-2025,Meghalaya,South West Khasi Hills,793114,0,6,0
1004464,31-12-2025,Meghalaya,West Garo Hills,794002,0,5,1
1004465,31-12-2025,Meghalaya,West Khasi Hills,793119,0,26,0